apiVersion: v1
kind: service
metadata:
   name: springjenkins-service
spec:
   type: NodePort
   selector:
      app: springjenkins
   ports:
    - port: 8086
      targetPort: 8086
      nodePort: 30007      